# name: 'Update CHANGELOG.md'
# description: 'Record information from pull request into CHANGELOG.md file.'

name: 'Bump semantic version'
description: 'Uses "npm" to bump a semantic version ("major", "patch" or "minor") and tag then at the end of a PR.'
inputs:
  branch:
    description: 'branch name which will be used to fetch log information, push commits and so on.'
    required: true
    default: 'release-candidate' # or "bugfix"
  version:
    description: 'semantic version which will be bumped, can be one of the following: "major", "patch" and "minor".'
    required: true
    default: 'minor'
runs:
  using: 'composite' # enable usage of multiple commands. See https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-composite-run-steps-action
  steps:
    - run: >
      git config --local user.email "action@github.com"
      git config --local user.name "GitHub action"
      git checkout ${{ inputs.branch }}
    shell: bash
